name: App CI

on:
  push:
    paths:
      - 'ejemplos/nodejs-app/**' # Solo se dispara si cambia algo en esta carpeta

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ejemplos/nodejs-app/package-lock.json
          
      - name: Install
        run: cd ejemplos/nodejs-app && npm ci
        
      - name: Test
        run: cd ejemplos/nodejs-app && npm test

      - name: Build Docker
        run: |
          cd ejemplos/nodejs-app
          docker build . -t test-app:latest
