# -*- coding: utf-8 -*-
"""elevenlabs_tts-audiomusic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y7abSyMIhGrBSJhqzQdh4WAfbiiV6wB9
"""

from google.colab import userdata
eleven = userdata.get('elevenlabs')

!pip install elevenlabs

from elevenlabs import ElevenLabs

client = ElevenLabs(
    api_key=eleven,
    base_url="https://api.elevenlabs.io"
)

#client.voices.search()

from dotenv import load_dotenv
from elevenlabs.client import ElevenLabs
import os
from google.colab import files

load_dotenv()

def createContents(textinfo)
  # 1. Generar el audio
  audio = client.text_to_speech.convert(
      text=textinfo,
      voice_id="rpqlUOplj0Q0PIilat8h",
      model_id="eleven_multilingual_v2",
      output_format="mp3_44100_128",
  )

  file_name = "saludo.mp3"

  with open(file_name, "wb") as f:
      for chunk in audio:
          f.write(chunk)

  print(f"Archivo guardado localmente en Colab: {file_name}")

  files.download(file_name)

  print("¡Descarga iniciada!")

createContents("textinfo")